%*********************************************************************** 
%									 
%	-- Read data from a file generated by the LabView application
%
%	-> Usage = 
%		-> [pow,time,att] = readAllMeasures(path,year,month,day)
%
%	-> inputs =
%		-> path  - STRING defining location of files
%		-> year  - STRING defining year
%		-> month - STRING defining month
%		-> day   - STRING defining day
%
%       OBS.: 'year', 'month' and 'day' must be either two-digit numbers
%       or '*' for wildcard
%	
%	-> outputs = 	
%		-> pow  - ARRAY OF FLOATS with measures of power (in dB)
%		-> time - ARRAY OF STRINGS with dates of measures
%		-> att  - ARRAY OF FLOATS with attenuation levels of each measure
%									 
%	-> MATLAB version used:	
%		- R2012b (8.0.0.783) 64-bit	
%				 
% 	-> Special toolboxes used: 
%		-- none	--
%
% 	-> Other dependencies: 
%		- myCell2Mat.m
%		- readMeasures.m
%									 
%	-> Created by Evandro Bernardes	 								 
%		- at ENSTA Bretagne (Brest, Britanny, France)							 								 
%		- In association with: 
%			ANFR - Agence Nationale de Fréquence    		 
%									 
% 	Code version:	1
%
%	last edited in:	26/07/2016 					 
%									 
%***********************************************************************

function [pow,time,att] = readAllMeasures(path,year,month,day)

    selectedFiles = sprintf('%s%s%s%s.txt', path, year, month, day);

    files = dir(selectedFiles);
    fileNames = [];
    n = length(files);
    for i=1:n
        fileNames = [fileNames; files(i).name];
    end

    pow = [];
    time = [];
    att = [];

    for i = 1:n

        ithFilePath = sprintf('%s%s', path, fileNames(i,:));
        [ithPow,ithTime,ithAtt] = readMeasures(ithFilePath);

        pow = [pow;ithPow];
        time = [time;ithTime];
        att = [att;ithAtt];
    end
end