%*********************************************************************** 
%									 
%	-- Read data from multiples files generated by the LabView application
%
%	-> Usage = 
%		-> [data,fileNames] = readAllMeasures(path,date)
%
%	-> inputs =
%		-> path  - STRING defining location of files
%		-> date  - STRING defining date in the format "YYMMDD"
%
%       OBS.: 'YY', 'MM' and/or 'DD' can be changed for '*' if any of 
%       them should be a wildcard
%
%	-> outputs = 	
%       -> data  - STRUC, containing the following 3 elements:
%          = pow  - ARRAY OF FLOATS with measures of power (in dB)
%          = time - ARRAY OF STRUCT with time of measures
%                   time.year     - year of measure
%                   time.month    - month of measure
%                   time.day      - day of measure
%                   time.hour     - hour of measure
%                   time.minute   - minute of measure
%                   time.second   - second of measure
%                   time.tthOfMil - tenths of miliseconds
%          = att  - ARRAY OF FLOATS with attenuation levels of each measure
%
%       -> fileNames ARRAY OF STRINGS with names of loaded files
%									 
%	-> MATLAB version used:	
%		- R2012b (8.0.0.783) 64-bit	
%				 
% 	-> Special toolboxes used: 
%		-- none	--
%
% 	-> Other dependencies: 
%		- myCell2Mat.m
%		- readMeasures.m
%									 
%	-> Created by Evandro Bernardes	 								 
%		- at ENSTA Bretagne (Brest, Britanny, France)							 								 
%		- In association with: 
%			ANFR - Agence Nationale de Fréquence    		 
%									 
% 	Code version:	8
%   - v2: correction of "time" struct
%   - v3: definition of "data" struct
%   - v4: insertion of date in "time" struct
%   - v5: insertion of sample in "time" struct
%   - v6: check for wildcard option
%   - v7: no more checking and changing of parameter to "date"
%   (more direct single string parameter)
%   - v8: correction of "tthOfMil" time component
%
%	last edited in:	24/08/2016 					 
%									 
%***********************************************************************

function [data,fileNames] = readAllMeasures(path,date)
    %% load files    
    filesSelection = sprintf('%s%s.txt', path, date);

    files = dir(filesSelection);
    %% initialize vectors
    pow = [];
    att = [];
    
    year = [];
    month = [];
    day = [];
    hour = [];
    minute = [];
    second = [];
    tthOfMil = [];
    
    fileNames = {};
   
    for i = 1:length(files)
        fileNames{i} = files(i).name;
        ithFilePath = sprintf('%s%s', path, files(i).name);
        ithData = readMeasures(ithFilePath);

        pow = [pow;ithData.pow];
        att = [att;ithData.att];
        
        year = [year;ithData.time.year];
        month = [month;ithData.time.month];
        day = [day;ithData.time.day];
        hour = [hour;ithData.time.hour];
        minute = [minute;ithData.time.minute];
        second = [second;ithData.time.second];
        tthOfMil = [tthOfMil;ithData.time.tthOfMil];    
    end
    
    %% final definition of data structure
    time = struct('year',year,'month',month,'day',day,'hour',hour,'minute',minute,'second',second,'tthOfMil',tthOfMil);
    data = struct('pow',pow,'time',time,'att',att);
end