%*********************************************************************** 
%									 
%	-- Read data from a file generated by the LabView application
%
%	-> Usage = 
%		-> data = readMeasures(filePath)
%
%	-> inputs =
%		-> filePath - STRING defining name and location of file
%	
%	-> outputs = 	
%       -> data struct, containing the following 3 elements:
%			pow  - ARRAY OF FLOATS with measures of power (in dB)
%			time - ARRAY OF STRUCT with time of measures
%                   time.YY   - year of measure
%                   time.MM   - month of measure
%                   time.DD   - day of measure
%                   time.hh   - hour of measure
%                   time.mm   - minute of measure
%                   time.ss   - second of measure
%                   time.ffff - tenths of miliseconds
%			att  - ARRAY OF FLOATS with attenuation levels of each measure
%									 
%	-> MATLAB version used:	
%		- R2012b (8.0.0.783) 64-bit	
%				 
% 	-> Special toolboxes used: 
%		-- none	--
%
% 	-> Other dependencies: 
%		- myCell2Mat.m
%									 
%	-> Created by Evandro Bernardes	 								 
%		- at ENSTA Bretagne (Brest, Britanny, France)							 								 
%		- In association with: 
%			ANFR - Agence Nationale de Fréquence    		 
%									 
% 	Code version:	9
%   - v2: addition of "myCell2Mat.m" script
%   - v3: substitution of string "time" type for struct
%   - v4: correction of "time" struct
%   - v5: definition of "data" struct
%   - v6: insertion of date in "time" struct
%   - v7: insertion of sample in "time" struct
%   - v8: correction of "tthOfMil" time component
%   - v9: modification of time structure component names
%
%	last edited in:	30/08/2016 					 
%									 
%*********************************************************************** 

% Function declaration
function data = readMeasures(filePath)
    %% loading of file
	fileID = fopen(filePath);
    fileName = dir(filePath); 
    fileName = fileName.name;
    
    %% read measures as strings
	pattern = '%s %s %s';
    rawData = textscan(fileID,pattern);
    
    %% extraction of "power" float array    
    pow = myCell2Mat(rawData{1});
    
    %% extraction of "attenuation" float array    
    att = myCell2Mat(rawData{3});
    
    %% extraction of "time" struct array    
    rawTime = cell2mat(rawData{2});
    
    hour = str2num(rawTime(:,1:2));
    minute = str2num(rawTime(:,4:5));
    second = str2num(rawTime(:,7:8));
    tthOfMil = str2num(rawTime(:,10:13));
    
    %% extract date in fileName
    n = length(pow);
    
    % extract year
    year = str2num(fileName([1 2]));
    year(1:n) = year;
    year = year';
    
    % extract month
    month = str2num(fileName([3 4]));
    month(1:n) = month;
    month = month';
    
    % extract day
    day = str2num(fileName([5 6]));
    day(1:n) = day;
    day = day';
    
    %% final definition of data structure
    time = struct('YY',year,'MM',month,'DD',day,'hh',hour,'mm',minute,'ss',second,'ffff',tthOfMil);
    data = struct('pow',pow,'time',time,'att',att);
end
